exports.STATUS_FOLLOWER = 'FOLLOWER';
exports.STATUS_FOLLOWING = 'FOLLOWING';

exports.AUTH_USER = 'AUTH_USER';
exports.UNKNOWN = 'UNKNOWN';
exports.FOLLOWER = 'FOLLOWER';
exports.FOLLOWING = 'FOLLOWING';
exports.INRELATIONSHIP = 'INRELATIONSHIP';